name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: team_Tn5OjGGBUZtKuxEDb6Nik6zm
  VERCEL_PROJECT_ID: prj_eUyn4DpMgcIAuSSDP0KTrG84vVO6
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=nv0lSHeRRVtZ0Xr3i2a0Sqkf
      - name: Build Project Artifacts
        run: vercel build --token=nv0lSHeRRVtZ0Xr3i2a0Sqkf
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=nv0lSHeRRVtZ0Xr3i2a0Sqkf
      